xiph/awcy

- www/index.html
Moved graph axes settings next to data settings, renamed a few list options (didn't change actual values though, so code doesn't break)
> Layout tweaks

- www/index.html
Just making it shrink for shorter file names.
> Tidy up video name listbox

- www/index.html
this only adds the run IDs to the URL, need to add URL parser to auto-select runs if URL parameters passed.
> Add run IDs to URL, more comments

- README.md
I specified a version on irc because `0.3.8` and up have more dependencies and these build instructions don't include those extra dependencies.
> Update readme setup instructions

- www/awcy.css
- www/index.html
The image will now show while it's loading. A background was added so the user can see when the image will be fully loaded.
The background could possibly cause problems I suppose if any images were partially transparent but I suppose that would be unusual. Maybe there are better options later but this seems to work for now.
> Show the image while it's loading

- www/awcy.css
- www/index.html
This moves the interface into a single column instead of 2 stacked columns. Runs are picked with left and right click. I tried to do it with left click only but it gets confusing to handle all the cases and more confusing to use.
I'm working towards getting a box with permanent references working but haven't gotten there yet. The auto-delete thing is also on my radar soon too.
I'm not really sure how to tag the reference runs yet. I think you said you tag them special but I'm not sure if you do it manually or one of the scripts handles them specifically.
> Single runid column

- www/index.html
This should fix the server issue and adds a few tweaks to make everything a little nicer.
> Minor fixes

- README.md
- generate_list.js
- www/index.html
I tested this and it seems to work properly. People have already asked about sorting the run_ids so that should be nice.
> Remove stale images

- generate_list.js
- www/awcy.css
- www/index.html
This supports having reference images as benchmarks for the future. It also fixes a couple minor things as well.
> Support reference images

- www/index.html
Hopefully fixes https://github.com/tdaede/awcy/issues/65 but haven't yet tested it yet. Should at least let IE parse the html more properly.
> Use for...in for compatibility with IE

- www/README.md
- www/src/components/FullReport.tsx
- www/src/components/JobSelector.tsx
- www/src/components/Widgets.tsx
- www/src/stores/Stores.ts
Make keyboard navigation easier, and remove multi-select.
> Keyboard Navigation

- www/package.json
- www/src/components/Report.tsx
Inline the report so you can easily copy sections from.
> Remove copy-to-clipboard.

- www/src/stores/Stores.ts
This fixes exception that occurred during startup.
> Return promise in loadStatus()

- www/src/components/SubmitJobForm.tsx
This fixes exception that occurred during startup.
> Prevent type-Os in command line args.

- www/src/components/SubmitJobForm.tsx
> Use the cli validation function.

- www/index.html
- www/src/components/Job.tsx
- www/src/components/SubmitJobForm.tsx
- www/src/stores/Stores.ts
When you press the details button on a job `...`, you now have the option to `Rerun` a previous job.
> Misc bug fixes.

- www/src/components/FullReport.tsx
- www/src/components/Plot.tsx
- www/src/stores/Stores.ts
> www: fix encoding time display

- www/src/analyzer.ts
- www/src/analyzerEntry.tsx
- www/src/components/Analyzer.tsx
- www/src/stores/Stores.ts
Add deringing and CLPF support.
Fix URI encoding bug.
Add analyzer local mode.
> New features and fixes.

- www/src/components/analyzer/Analyzer.tsx
> Fix reference frame reporting.

- www/analyze.js
- www/package.json
- www/src/components/analyzer/Analyzer.tsx
Fixes #143 once https://aomedia-review.googlesource.com/c/9680/ lands. This can be merged before the gerrit patch lands.
Also, adds electron shell.
> Add tile grid view and electron shell.

- www/src/stores/Stores.ts
Stops timeSince from rounding up things like 30.00...01 minutes to 1 hour and 30 minutes. Adds second level precision when there is less than a minute difference.
> Fix off by one errors in timeSince.

- README.md
- etc/entrypoint
- www/src/components/SubmitJobForm.tsx
it's the format a lot of repositories use
> allow short hashes

- www/src/components/Jobs.tsx
- www/src/components/SubmitJobForm.tsx
> www: rename "Codec" placeholder to "Encoder"

- Dockerfile
This adds support for decoding rav1e output with dav1d from https://github.com/xiph/rd_tool/pull/51.
> Update Dockerfile to build dav1d

- etc/entrypoint
> Revert "Fix Cargo registry write permissions with Docker"

- Dockerfile
Fixes #193
I'm not sure how to test this patch, so I can't guarantee that it works. It might also be worth it to use this version of VMAF when computing VMAF scores.
> Build and install VMAF

- Dockerfile
> docker: fix emsdk build stage

- www/src/stores/Stores.ts
> Handle JSON which contains Python-style Infinity values.

- Dockerfile
> Add package-lock.json to Docker image.

- Dockerfile
- awcy_server.ts
- csv_export.py
- etc/entrypoint
- www/src/components/Job.tsx
- www/src/components/Jobs.tsx
- www/src/components/Report.tsx
- www/src/components/SubmitJobForm.tsx
- www/src/stores/Stores.ts
This PR Introduces support for Multiple CTC set transcode option and download an XLSM file for the CTC, 
Note that this is not fully tested as I do not have big clusters, so I am staging the PR for review, 
Secondly, there is additional commits from #313 which is required for this MR to be merged as standalone.
Edit:
Screenshots:
In the backend, we are creating a folder each for different video set, and assigning first video-set as 'task' for front-end rendering.
> Introduce Support for Multi-CTC Set transcode 

- awcy_server.ts
- bd_rate_report.py
- csv_export.py
- www/src/components/Job.tsx
- www/src/components/SubmitJobForm.tsx
- www/src/stores/Stores.ts
This follows similar changes as multisite but this introduces additional new layer of Folder structure, 
Tested on VLC12 for most of the cases, including backward compatibility and XLSM generation with different levels of encode-jobs. 
This depends on RD_TOOL PR for backend changes. 
Screenshots:
> CTC: Introduce Multi Config support

- csv_export.py
Non-AVM codecs can give ctc options in frontend and can cause 502 with a server crash, so handle that case and make sure we do stdout for ctcsets for csv output too.
Tested temp on running instance for hot-verification
> csv_export: Handle non-avm codecs

- awcy_server.ts
This depends on the new API endpoint of rd_server in https://github.com/xiph/rd_tool/pull/142
> server: Invoke email notifications for failed jobs

- csv_export.py
This found to be useful for rav1e development, so why not:)
> csv_export: Include rav1e for CTC exports

- www/src/components/Jobs.tsx
- www/src/components/Report.tsx
Helps to search certain jobs based on preset for example,
Edit; Second commit is a simple edit to add (%) sign to the fronted
> www/Jobs: Introduce ExtraOptions Filter

- Dockerfile
- Dockerfile.worker
- awcy_server.ts
- csv_export.py
- www/src/components/Report.tsx
- www/src/components/SubmitJobForm.tsx
- www/src/stores/Stores.ts
Frontend changes, for UI buttons
Depends on https://github.com/xiph/rd_tool/pull/163
> AOM: Update to AOM-CTC v6

- www/src/components/SubmitJobForm.tsx
This renames RA/AI/LD with codec prefix, and add VVC to multi-codec options, and show
only VVC if VVC* is selected, and same for AVM* codecs
https://github.com/xiph/awcy/assets/10833993/bfbb5470-8d3b-47d7-8aa5-86d951354508
Would rebase once the #367  is landed
> www/SubmitJobForm: Introduce VVC in the multi-options and filter adaptively
