- awcy_server.js
This swaps to `LANG` though I probably could have just added it. I have no preference either way.
> Switch from PYTHONIOENCODING to LANG environmental

- awcy_server.js
- generate_list.js
- run_video_test.sh
- run_video_test2.sh
- www/awcy.css
- www/index.html
This seems to work pretty well. It compares two run ids at the same bitrate with the same picture. Things get a little weird if both sets don't have the same image sets or bitrates which can get confusing.
I'm using bpp of 0.1:0.1:1.0 as my ranges. Is that the range that you would use? I can change it. I'd prefer if it be set to something really good for now so it doesn't have to be changed later.
rd_tool probably needs to compress the images so they don't take up so much space. Maybe imagemagick will do it? I'm not really sure but it seems like a good idea to check before this is uploaded.
I might be able to consolidate some things...I'm not really sure but I think I'm done with it for today.
> Image comparison tool

- www/index.html
The images tab currently shows up blank when you switch to it. Better to default to subset1 where most of the images are.
> Set default image subset to subset1

- www/package.json
- www/src/components/Report.tsx
This adds the ability to copy copy-and-paste friendly BD reports to the clipboard, such as:
| PSNR | PSNR Cb | PSNR Cr | PSNR HVS | SSIM | MS SSIM | CIEDE 2000 |
| ---: |    ---: |    ---: |     ---: | ---: |    ---: |       ---: |
| 0.04 |   -1.12 |   -1.09 |     0.26 | 0.09 |    0.32 |      -0.33 |
|                                                        Video |  PSNR | PSNR HVS |  SSIM | MS SSIM | CIEDE 2000 | PSNR Cb | PSNR Cr | APSNR | APSNR Cb | APSNR Cr |
|                                                         ---: |  ---: |     ---: |  ---: |    ---: |       ---: |    ---: |    ---: |  ---: |     ---: |     ---: |
|             Netflix_Aerial_1920x1080_60fps_10bit_420_60f.y4m | -1.73 |    -1.99 | -1.44 |   -1.41 |      -1.29 |   -0.80 |   -0.08 | -1.68 |    -0.78 |    -0.12 |
| …
> Add Copy to Clipboard support.

- www/src/components/Job.tsx
This can be abused by overloading the queue and potentially injecting dangerous cli command (haven't tested)
> Prevent non-logged in user from rerunning jobs

- Dockerfile
It responds slowly and we already have the ubuntu one, which is required
for ubuntu packages.
> Drop pgp.mit.edu keyserver.

- Dockerfile
No practical difference, this just avoids relying on GitHub redirecting to the correct location.
> Fetch rd_tool from xiph rather than tdaede

- etc/entrypoint
For some reason the permissions can change when the container is restarted, so this
sets the permissions when starting the container, instead of only at build time.
> Fix Cargo registry write permissions with Docker

- Dockerfile.worker
This is needed to decode rav1e output and detect desyncs. libaom is not installed on workers either, so the fallback to aomdec also fails, and the encoding process is aborted as a result.
> Install dav1d on Docker workers

- awcy_server.ts
- build_codec.sh
- www/src/components/SubmitJobForm.tsx
As far as I can tell, there's no reason to restrict the field to a commit, since the reference is fed directly to `git checkout`. This allows users to enter a tag or a branch name instead.
Also removes unnecessary build steps for rav1e, since it no longer uses a submodule.
> Allow building codecs from any reference

- Dockerfile
Rationale: 2.14.02-1 is no longer available from the debian mirror.
> docker: update to nasm 2.15.02

- bd_rate_report.py
- www/src/components/Report.tsx
Set the default displayed metrics to the  AV2 metrics.
Set overflow-y for the raw and bdrate tables.
> Fix BD-Rate offsets and formatting.

- bd_rate_report.py
> Avoid encode/decode time divide by zeros for runtimes that are 0.

- bd_rate_report.py
encode_times_a is an array, which can't be compared to 0.
> Fix divide by zero exception again.

- www/src/components/Jobs.tsx
This commit introduces option to filter based on job_name,
Right now can search for job and list in the main list of jobs for selection.
Also enable to select multiple jobs
Screenshots:
> Jobs: Introduce Job Name filter

- Dockerfile
- Dockerfile.worker
Fix same problem as e338be610a70d79e42ba27647108129438d6682b in the
rav1e tree; new version of clamp crate can't build with older Rust.
Update Rust in Docker build to 1.51.0.
> Update minimum rust version in Docker files

- Dockerfile
- Dockerfile.worker
This is needed for the latest version of rav1e to compile.
> Update the Rust version to 1.59

- Dockerfile
- Dockerfile.worker
- etc/entrypoint
This PR introduces
- support for building Docker for ARM target, this is tested on M1 mac, 
- ~Updates some packages and locks to make sure it is compatible with modern changes, this is also disabling IRC module as I was not able to build it anymore as we are on steps to migrate to Email based notifcation but would be nice to make it not broken.~
- Migrates to latest CTCv3 VMAF, HDRTools versions
I have removed www/ irc module disabling in this, so we can land this first.
> Add ARM building support for Docker and other misc updates

- awcy_server.ts
- csv_export.py
- www/src/App.tsx
- www/src/components/Debug.tsx
- www/src/components/SubmitJobForm.tsx
Users could select cross-codec/preset as A/B, that should not mean both should be written against base-codec preset, write them into actual target(LD/AI/RA).
This commit also amennds fileName to have current upstream CTC Document version.
We could see this in two ways, 
a) without this change, we could still get full CTC comparison b/w two preset-configs but in wrong title which is a way to do some comparisons too which will not be possible. 
b) With this, it writes things to appropriate sheets irrespective of codec, so if we want we can modify it from sheet to different ones,
In both cases, we get the BD-Rate and most of the analysis from the frontend.
> server/csv_export: Make sure we store selected runs into desired sheet

- awcy_server.ts
- build_codec.sh
Probably Fixes https://github.com/xiph/awcy/issues/311
> build_codec: use gcc/g++ for svt-av1

- csv_export.py
Previosuly the F1/F2 was not correctly parsed, ie. it was giving exception which was
an edge-case which missed initial testing.
This also depends on the rd_tool patches which address QP point change for F1/F2.
> csv_export: Parse F1/F2 correctly 

- awcy_server.ts
- package.json
- www/src/components/Report.tsx
This uses `archiver` package to compress on-demand, 
We are using Level-4 right now,, we can increase/decrease it overtime based on demand/speed/other reasons when doing via beta as the beta is not big like runners(or test server)
In the server, we are prefixing jobs with `awcy_$run_id` for easy tracking, while frontend we just have run_id for better UX.
Screenshots:
Edit:
You can test it from VLC12 AWCY instance here: http://vlc12.xiph.osuosl.org:3000/
> Introduce Zipping and downloading Jobs on-demand

- build_codec.sh
This is necessary for enabling additional Cargo features.
> Pass $BUILD_OPTIONS parameter for rav1e

- awcy_server.ts
Current nodejs version deployed v12.X have 2min timeout https://nodejs.org/docs/latest-v12.x/api/http.html#http_server_settimeout_msecs_callback
For CTC processing it takes more than that, so we require to set the timeout more than that, currently setting to 10mins which is a lot but okay for now,
Ideally we do not want such long waits, we want to split this into two, one API to initiate the geneartion, second API to send file on completition in form of second button.
> server: Explicitly set the http.server timeout instead of default(2mins)

- Dockerfile.worker
- bd_rate_jm.py
- bd_rate_report.py
- bd_rate_report_as.py
- csv_export.py
- www/src/components/SubmitJobForm.tsx
This PR adds frontend and server changes for
+ MD5Sum for EncodeJob
+ This also moves to parse the texts with help of `genfromtxt` instead of `loadtxt` as we have non-numerical entries in daala.out and for BDR computation, we ignore them. 
+ Perf Support, workers require to have them installed, and runners should have non-root support for using `perf stat`, can enable that using `sudo sh -c 'echo 1 >/proc/sys/kernel/perf_event_paranoid`, we need this for measuring,
+ Encoding, Decoding Cycles
+ Encoding, Decoding Instruction Count
+ CSV_Export: 
+ Fixes a bug in All Preset option which was parsed in wrong way where the `task` was not updated
+ Fixes a bug where custom QP was not written to CSV_file
+ Clarified frontend to be more explicit to say AOM-CTC, since we have other CTC support.
> Add MD5, Perf Support and parse the values

- awcy_server.ts
- build_codec.sh
- csv_export.py
- etc/entrypoint
- www/src/stores/Stores.ts
This is dependent on the rd_tool changeset for the same set of support
Right now, we have RA, LD, AI, and also GOP Parallel. The QPs and cofigs are not fine-tuned but should be okay to have JVET_CTC as it is first.
This also unbreaks the CTC_CSV Export but XLSM will be broken due to uneven QPs
> awcy: Add VVC_VTM support

- www/src/components/SubmitJobForm.tsx
This was a small-bug which was found, when we push the unsorted code-path,
we will have problems in backend on doing the average.sh part, this addresses
the bug, (https://github.com/xiph/rd_tool/pull/133) 
Secondly, as  having email support in backend(via SMTP), so for that, we
are assuming they feed XXX@YYY.ZZZ email, so we will send notifications
via that. (https://github.com/xiph/rd_tool/pull/132)
> Push the current List and mention Email in the Frontend

- csv_export.py
- www/src/stores/Stores.ts
Previously if we have av2-all as preset, the paths were broken.
For av2-all cases of CTC XLSM Export, numerous fixes were addressed, they are
+ QP assignment for av2-ai
+ Previously condition for folder-based config path search,
was for length is >1 when we have av2-all, it is not true, handle them
+ Make sure we revert back to Anchor/Test-* sheet names after still images,
this was a case when still images were in middle and G1/G2 was written in the still sheet,
+ Avoid re-rewriting if the config list is the same for both runs, this saves a lot of
time.
> www: Fix path for av2-all case in frontend and handle CTC Export correctly

- awcy_server.ts
- csv_export.py
- www/src/components/Report.tsx
This adds both export logs and frontend changes for showing stdout of ctc export
The stdout is written to a .txt file and frontend polls 5 for showing it, overall it takes ~10-12 wallclock time  for showing the output, given beta is slow for generating this, this helps to keep track of it and avoid multiple ctc requests to backend from users. 
Screenshots:
PS: This contains commit from #337 which will be rebased after merge.
> server: Periodically display stdout of CTC-XLSM output 

- awcy_server.ts
- bd_rate_report_as.py
- csv_export.py
- etc/entrypoint
- www/src/components/Report.tsx
- www/src/stores/Stores.ts
This patchset enables AS preset for VVC along with various bug fixes to CSV_Export,
+ Do not lower-case when writing
This creates a problem for Class E where two sequences were flipped
+ Explicit cast of perf-stat when writing to CSV/XLSM file
This avoids treating the last col as Text
+ Do not write A1-4K for LD
+ Write VVC-VTM AS config
Depends on https://github.com/xiph/rd_tool/pull/145
> Add VVC-VTM-AS preset and bug-fixes to csv-export

- build_codec.sh
- www/src/components/Report.tsx
> build: Restrict VVC builds to 8 cores and improve frontend polling

- awcy_server.ts
- www/src/components/Job.tsx
- www/src/stores/Stores.ts
Two main things
a) Improve the submission job tracker, if we do not store the job-submission time, we will be replacing the value with the newly finished job from the multi-set/config queue. 
So we can start saving the submission time to info.json
For backward compatibility, if the information is not there, "date" information is used as "submit_time".
b) Improve the running job counter, this relies on the rd_tool patchset(backend) https://github.com/xiph/rd_tool/pull/147, where for a given job we introduce a multi-job tracker.
> Job tracker improvements

- awcy_server.ts
Before this change, only the first was being replaced. Fixes #27 and #197.
> awcy: replace all spaces in run name with _

- awcy_server.ts
- csv_export.py
- www/src/components/Report.tsx
Weirdly CTCv4 have a new filename for Regular, and not for AS, but it is how it is.
Maybe we need to think of migrating this to a new environment variable to reduce the noise in the repo if the updates are too frequent.
> awcy: Migrate to CTC-V4

- Dockerfile
- package-lock.json
- package.json
This also updates the package-lock.json and version.
> Update sqlite3 so it builds on recent node.

- csv_export.py
- www/src/components/SubmitJobForm.tsx
This set is made of two parts,
Part A:
CTC now reached a stage where the clipList is of different styles like,
a) CLIPNAME, b) ClipName, c) clipName, d) clipname, e) Clip_name, and
many other variants of stying for sequences name.
Handling all of them is now impossible without modifying clip names.
So let's trust and do the hardcoding of the clip in the exact order we want.
Part B:
We also add RA-GOP parallel to UI
> Deprecate sorting and add GOP-Parallel to CTC grid

- bd_rate_report.py
This was found to be missing in the CTC file-path handling, this enables bdr computation for non-parallel GOP and parallel GOP runs.
Eg, `av2-ra` and `av2-ra-st` is problematic in the current master,
```python
Traceback (most recent call last):
File "./bd_rate_report.py", line 420, in <module>
args.fullrange,
File "./bd_rate_report.py", line 275, in bdrate
b = genfromtxt(file2)
File "/home/awcybeta/.local/lib/python3.6/site-packages/numpy/lib/npyio.py", line 1749, in genfromtxt
fid = np.lib._datasource.open(fname, 'rt', encoding=encoding)
File "/home/awcybeta/.local/lib/python3.6/site-packages/numpy/lib/_datasource.py", line 195, in open
return ds.open(path, mode, encoding=encoding, newline=newline)
File "/home/awcybeta/.local/lib/python3.6/site-packages/numpy/lib/_datasource.py", line …
```
> bd_rate: Compute BD-Rate between Sequential and Parallel runs

- awcy_server.ts
- csv_export.py
- www/src/components/Job.tsx
- www/src/components/Report.tsx
- www/src/components/SubmitJobForm.tsx
- www/src/stores/Stores.ts
This adds support to a CTC version toggle, 
Now the AWCY also supports CTCv4.0 and CTCv5.0 at the same time. 
This needs a subsequent backend change with https://github.com/xiph/rd_tool/pull/155
> AOM: Introduce CTC version toggle and add support to CTCv5.0 in XLSM export

- www/src/components/JobSelector.tsx
This is for the graphs
This will match the BDR table now, and reduce non-libvmaf metrics.
> www/JobSelector: Display only ReportedMetrics (libvmaf) only

- awcy_server.ts
- www/src/stores/Stores.ts
Previously we used execFile, it is fine as long as the csv generation is fast, when we start to do with 6k+ files, it is buggy + slow + impossible to get the reuslts (eg. 2.7MB CSV file). So, we can spawn a process, append the data to a varaible, wait till it is completed, and then spit it out.
PS: ExecFile is problematic when we read file-by-file for 6k+ files over network disk, (like main beta server)
This now matches how we do for XLSM export
Secondly, we now restrict the frontend to load only 20 videos instead of 5k/6k videos
> server: Optimise CSV Export and Frontend loading

- create_test_branch.sh
- www/src/components/SubmitJobForm.tsx
Now Commit field is mandatory,
We also introduce support to submit run with HEAD
> Do not allow to submit runs without COMMIT ID

- www/src/App.tsx
- www/src/components/Job.tsx
- www/src/components/Report.tsx
- www/src/components/SubmitJobForm.tsx
Hi,
Few changes
+ Disable AWS buttons as we never use them
+ Only show Analyzer section for AV1 codecs as it simply do not work for others (yet)
+ Do not have the arch toggle, depends on https://github.com/xiph/awcy/pull/360 and https://github.com/xiph/rd_tool/pull/160
+ Avoid showing A/B compare as false all the time, 
+ Show the Task as Set as that is how we submit the job
> UI Tweaks to make better UX
